### ISSUE TITLE
Sound Physics starting in .. [1.18.1]

### ISSUE THREAD

**Issue by TheSnowyChickens** [vlad2305m/Sound-Physics-Fabric#37]
Hello,

in the nether your sound engine "can't start". (I think it is only the "chat" message)
It is not a loop, but it starts with 7k+ seconds and count down.

After returning to overworld ->
![grafik](https://user-images.githubusercontent.com/29357962/145871507-2ba73767-3fc1-499a-9371-4313a742db8a.png)

Nether ->
![grafik](https://user-images.githubusercontent.com/29357962/145870685-6ba99152-ae2f-401e-a934-fbc42b2708f5.png)

![grafik](https://user-images.githubusercontent.com/29357962/145870822-a4e2d097-7614-4328-94a3-03013552626e.png)
Fabric: fabric-loader-0.12.11-1.18.1

**Comment by thedocruby** [comment]
@vlad2305m Since this is your code I'll let you take care of it. I've had at least five people report this issue in the last 48 hours, between GitHub and CurseForge.

**Comment by thedocruby** [comment]
Fixed in most recent release (v0.5.1)

**Comment by TheSnowyChickens** [comment]
Hello,
sadly not fixed. :(
![grafik](https://user-images.githubusercontent.com/29357962/146266290-d1ae447d-66ec-400e-8de9-aea4c8bf79ff.png)

![grafik](https://user-images.githubusercontent.com/29357962/146266346-a6490466-5ee8-4ad2-bfc9-674a2fd6fe87.png)

**Comment by vlad2305m** [comment]
@TheSnowyChickens Does it increase/change occasionally without switching dimensions by any chance?

**Comment by thedocruby** [comment]
@TheSnowyChickens I am not able to reproduce this on my machine in the newest version. Could you send me some information about your system? What CPU are u using, what operating system, what java version, etc.
Also, make sure your drivers are up-to-date, and please send a screenshot in-game of ModMenu displaying SoundPhysics version 0.5.1 to verify you are using an updated version. Also, please check if you are using any mods or datapacks that affect nether portals (e.g. Nether Spawn or Immersive Portals) and also check if you have any mods or datapacks that add custom dimensions or world types. Finally, launch the game with version 0.5.1 and enable all debug logging, reproduce the bug, and quit the game. Then upload the log file here. With all of this information available I should be able to discern the problem.

**Comment by TheSnowyChickens** [comment]
System: 8700k on a Gigabyte Gaming X mainboard, 780 TI, Win10 (on a M.2) (Minecraft on HDD)

About the MC server: it is a Vanilla server with some datapacks from VanillaTweaks.
(Yes, we have the custom portals datapack installed, but this doesn't change anything in the dimension)

The new "high number" was not there from the beginning, I was long enough in the nether and then I walked to my ancient debris area and it started to display the high number.

![grafik](https://user-images.githubusercontent.com/29357962/146285746-2f7179a5-cbe6-4c5e-a0e4-68a009d3881c.png)

I can't rly say how, because it is now a few hours ago, but I will look carefully at it if it happens again.

And to your first message: it counts down in a normal speed.

**Comment by vlad2305m** [comment]
Since it is so rare, I have written a small line to get rid of it post-factum.

**Comment by thedocruby** [comment]
I agree, client-server desync seems to be the obvious culprit here. I will leave the issue open until Vlad's one-liner is released.

**Comment by TheSnowyChickens** [comment]
Ty

**Comment by vlad2305m** [comment]
> Ty

What?

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/146626522-edee8389-253f-4862-a972-208753002d9a.png)

last update: I did rly NOTHING this time, I only walked in my afk room and then afk.

And: "Ty" = "Thank You"

**Comment by vlad2305m** [comment]
v0.5.2 I removed it since it doesn't work. You can do it manually with the topmost config button if the game lags too much, or by pressing esc in singleplayer. Luckily, the issue of too many sound piling up and freezing the game is fixed.
